@extends('userlayout')

@section('content')

    <!--start About Us-->
    <div class="about-us">
        <div class="text">
            <h3>Our Story</h3>
            <p>TourViet is proud to be the organizer of tours that have been trusted by
                hundreds of travel
                companies across the country for a long time and have used the service to
                provide customers
                from near and far. <br>
                With abundant resources: diverse services, products, strong finance, thoughtful
                customer
                care policies, 4.0 technology application, sustainable relationship with major
                partners
                around the world , dynamic and professional staff - Tourviet always strives to
                bring
                customers the most valuable tourism products.</p>
        </div>
        <div class="image-container">
            <div class="image image1">
                <img src="https://images.pexels.com/photos/2325446/pexels-photo-2325446.jpeg?auto=compress&cs=tinysrgb&w=600" alt="Photo">
            </div>
            <div class="image image2">
                <img src="https://images.pexels.com/photos/507410/pexels-photo-507410.jpeg?auto=compress&cs=tinysrgb&w=600" alt="Photo">
            </div>
        </div>
    </div>
    <!--End About Us-->

    <!--start Recipes-->
    <div class="recipes">
        <div class="image"></div>
    </div>
    <!--End Recipes-->

    <!--start Menu-->
    <div class="menu">
        <div class="box-model">
            <div class="box-image-container">
                <div class="box-image">
                    <img src="" alt="Photo">
                </div>
            </div>
        </div>
        <div class="menu-image-container">
            <div class="image active">
                <img  src="https://images.pexels.com/photos/3155666/pexels-photo-3155666.jpeg?auto=compress&cs=tinysrgb&w=600g" alt="Photo">
            </div>
            <div  class="image">
                <img src="https://images.pexels.com/photos/1591373/pexels-photo-1591373.jpeg?auto=compress&cs=tinysrgb&w=600" alt="Photo">
            </div>
            <div class="image">
                <img height="400px" src="https://images.pexels.com/photos/4553618/pexels-photo-4553618.jpeg?auto=compress&cs=tinysrgb&w=600" alt="Photo">
            </div>
            <div class="image">
                <img height="400px" src="https://images.pexels.com/photos/2440009/pexels-photo-2440009.jpeg?auto=compress&cs=tinysrgb&w=600" alt="Photo">
            </div>
        </div>
        <div class="text">
            <h3>Tourism in the economy</h3>
            <p>Tourism is important in Vietnam. For backpackers, culture and nature lovers, beach-lovers, military
                soldiers and veterans, Vietnam has become a new tourist destination in Southeast Asia. Local and
                international tour operators offer tours to ethnic minority groups, walking and bicycle tours,
                photography tours, kayak trips and multi-country trips in particular with neighboring Cambodia, Laos and
                Thailand. Foreign tourists have been able to travel freely in the country since 1997.
                <br><br>
                The economy of Vietnam has transformed from an agrarian to a service economy. More than a third of gross
                domestic product is generated by services, which include the hotel and catering industry and
                transportation. The manufacturing and construction (28 percent), agriculture and fisheries (20 percent)
                and mining (10 percent) have much smaller shares.</p>
        </div>
    </div>
    <!--End Menu-->

    <!--Start fixed-image-->
    <div class="fixed-image">

    </div>
    <!--End fixed-image-->

    <!--start About Us-->
    <div class="reservation">
        <div class="text">
            <h3>Tourism in Vietnam</h3>
            <p>Tourist arrivals in Vietnam have continued to rise in recent years. In 2008, Vietnam received 4.218
                million international tourists, in 2009 the number was 3.8 million, down 11%. In 2012, Vietnam received
                6.84 million tourists.This was a 13% increase from 2011 figure of 6 million international visitors,
                which was itself a rise of 2 million visitors relative to 2010 arrivals. In 2016, Vietnam welcomed 10
                million international visitors which represented a 26% increase from the previous year.</p>
        </div>
        <div class="image-container">
            <div class="image image1">
                <img height="250px" src="https://images.pexels.com/photos/2549018/pexels-photo-2549018.jpeg?auto=compress&cs=tinysrgb&w=600" alt="Photo">
            </div>
            <div class="image image2">
                <img height="250px" src="https://images.pexels.com/photos/1457812/pexels-photo-1457812.jpeg?auto=compress&cs=tinysrgb&w=600" alt="Photo">
            </div>
        </div>
    </div>
    <!--End About Us-->

@endsection

@section('title')
    About
@endsection

@section('linkcss')
    {{asset('css/user/about.css')}}
@endsection

@section('linkjs')

@endsection
